/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Connection {
  static open(name: string): Connection
  isAlive(): boolean
  getSysInfo(flags: number): string
  getMaxVcpus(attr: string): number
  getCpuModelsNames(arch: string, flags: number): Array<string>
  isEncrypted(): boolean
  isSecure(): boolean
  listActiveDomainIds(): Array<number>
  listInterfaces(): Array<string>
  listNetworks(): Array<string>
  listNwFilters(): Array<string>
  listSecrets(): Array<string>
  listStoragePools(): Array<string>
  listAllDomains(flags: number): Array<Machine>
  listAllNetworks(flags: number): Array<Network>
  listAllInterfaces(flags: number): Array<Interface>
  listAllNodeDevices(flags: number): Array<NodeDevice>
  listAllSecrets(flags: number): Array<Secret>
  listAllStoragePools(flags: number): Array<StoragePool>
  listAllNwFilters(flags: number): Array<NWFilter>
}
export class Machine {
  static fromName(name: string, con: Connection): this
}
export class Network { }
export class Interface { }
export class NodeDevice { }
export class Secret { }
export class StoragePool { }
export type NWFilter = NwFilter
export class NwFilter { }
