/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'libvirt.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./libvirt.android-arm64.node')
          } else {
            nativeBinding = require('@infinibay/libvirt-node-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'libvirt.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./libvirt.android-arm-eabi.node')
          } else {
            nativeBinding = require('@infinibay/libvirt-node-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'libvirt.win32-x64-msvc.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./libvirt.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@infinibay/libvirt-node-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(join(__dirname, 'libvirt.win32-ia32-msvc.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./libvirt.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@infinibay/libvirt-node-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'libvirt.win32-arm64-msvc.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./libvirt.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@infinibay/libvirt-node-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'libvirt.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./libvirt.darwin-universal.node')
      } else {
        nativeBinding = require('@infinibay/libvirt-node-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'libvirt.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./libvirt.darwin-x64.node')
          } else {
            nativeBinding = require('@infinibay/libvirt-node-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'libvirt.darwin-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./libvirt.darwin-arm64.node')
          } else {
            nativeBinding = require('@infinibay/libvirt-node-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'libvirt.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./libvirt.freebsd-x64.node')
      } else {
        nativeBinding = require('@infinibay/libvirt-node-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'libvirt.linux-x64-musl.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./libvirt.linux-x64-musl.node')
            } else {
              nativeBinding = require('@infinibay/libvirt-node-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'libvirt.linux-x64-gnu.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./libvirt.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@infinibay/libvirt-node-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'libvirt.linux-arm64-musl.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./libvirt.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@infinibay/libvirt-node-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'libvirt.linux-arm64-gnu.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./libvirt.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@infinibay/libvirt-node-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'libvirt.linux-arm-musleabihf.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./libvirt.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@infinibay/libvirt-node-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'libvirt.linux-arm-gnueabihf.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./libvirt.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@infinibay/libvirt-node-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'libvirt.linux-riscv64-musl.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./libvirt.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@infinibay/libvirt-node-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'libvirt.linux-riscv64-gnu.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./libvirt.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@infinibay/libvirt-node-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(join(__dirname, 'libvirt.linux-s390x-gnu.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./libvirt.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@infinibay/libvirt-node-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const {
  Connection,
  Machine,
  MachineInfo,
  Time,
  StateResult,
  BlockInfo,
  InterfaceStats,
  MemoryStat,
  NumaParameters,
  MemoryParameters,
  Network,
  Interface,
  NodeDevice,
  Secret,
  StoragePool,
  StorageVol,
  NwFilter,
  NodeInfo,
  DomainStatsRecord,
  VirDomainGetHostnameFlags,
  VirDomainXMLFlags,
  VirDomainCreateFlags,
  VirDomainDefineFlags,
  VirDomainDestroyFlags,
  VirDomainRebootFlag,
  VirDomainUndefineFlags,
  VirDomainModificationImpact,
  VirDomainMemoryModFlags,
  VirStoragePoolCreateFlags,
  VirStorageXMLFlags,
  ErrorLevel,
  ErrorDomain,
  ErrorNumber,
  Error,
} = nativeBinding

module.exports.Connection = Connection
module.exports.Machine = Machine
module.exports.MachineInfo = MachineInfo
module.exports.Time = Time
module.exports.StateResult = StateResult
module.exports.BlockInfo = BlockInfo
module.exports.InterfaceStats = InterfaceStats
module.exports.MemoryStat = MemoryStat
module.exports.NumaParameters = NumaParameters
module.exports.MemoryParameters = MemoryParameters
module.exports.Network = Network
module.exports.Interface = Interface
module.exports.NodeDevice = NodeDevice
module.exports.Secret = Secret
module.exports.StoragePool = StoragePool
module.exports.StorageVol = StorageVol
module.exports.NwFilter = NwFilter
module.exports.NodeInfo = NodeInfo
module.exports.DomainStatsRecord = DomainStatsRecord
module.exports.VirDomainGetHostnameFlags = VirDomainGetHostnameFlags
module.exports.VirDomainXMLFlags = VirDomainXMLFlags
module.exports.VirDomainCreateFlags = VirDomainCreateFlags
module.exports.VirDomainDefineFlags = VirDomainDefineFlags
module.exports.VirDomainDestroyFlags = VirDomainDestroyFlags
module.exports.VirDomainRebootFlag = VirDomainRebootFlag
module.exports.VirDomainUndefineFlags = VirDomainUndefineFlags
module.exports.VirDomainModificationImpact = VirDomainModificationImpact
module.exports.VirDomainMemoryModFlags = VirDomainMemoryModFlags
module.exports.VirStoragePoolCreateFlags = VirStoragePoolCreateFlags
module.exports.VirStorageXMLFlags = VirStorageXMLFlags
module.exports.ErrorLevel = ErrorLevel
module.exports.ErrorDomain = ErrorDomain
module.exports.ErrorNumber = ErrorNumber
module.exports.Error = Error
